import type { AppState, CompanionOutput } from "../types";
import { getUserToday, dateOffset } from "../utils/dates";

const EMOTIONAL_PATTERNS: Record<string, RegExp[]> = {
  stressed: [/\b(stressed|overwhelmed|too much|can't handle|drowning)\b/i],
  frustrated: [/\b(frustrated|annoyed|angry|ugh|ridiculous)\b/i],
  low_energy: [
    /\b(tired|exhausted|drained|no energy|burned out|burnout)\b/i,
  ],
  positive: [/\b(great|amazing|awesome|nailed it|crushed it|on fire)\b/i],
  anxious: [/\b(worried|anxious|nervous|scared|dreading)\b/i],
  venting: [/\b(just needed to say|venting|rant|what a day)\b/i],
};

const FRICTION_SIGNALS: Record<string, (state: AppState) => boolean> = {
  overdue_pile: (s) => s.hotContext.overdueCount >= 3,
  task_overload: (s) => s.hotContext.openTaskCount >= 20,
};

/**
 * Detect emotional signals BEFORE the LLM call.
 * Returns context to inject into the LLM payload, or null if no signals.
 */
export function checkEmotionalTone(
  phrase: string,
  state: AppState
): CompanionOutput | null {
  const emotions = Object.entries(EMOTIONAL_PATTERNS)
    .filter(([, patterns]) => patterns.some((p) => p.test(phrase)))
    .map(([emotion]) => emotion);

  const friction = Object.entries(FRICTION_SIGNALS)
    .filter(([, check]) => check(state))
    .map(([name]) => name);

  if (emotions.length === 0 && friction.length === 0) return null;

  return {
    emotions,
    friction,
    supportNote: "", // No longer generated by TypeScript — LLM decides what to say
    energyEstimate: estimateEnergy(emotions),
  };
}

/**
 * Build a companion context snapshot for the planning LLM.
 * This gives the LLM everything it needs to generate the CompanionBrief
 * section of the focus brief. Called by the assembler for full_planning.
 *
 * TypeScript gathers the data. LLM does the judgment.
 */
export function buildCompanionContext(state: AppState): Record<string, unknown> {
  const ctx: Record<string, unknown> = {};

  // Current state signals
  ctx.overdueCount = state.hotContext.overdueCount;
  ctx.openTaskCount = state.hotContext.openTaskCount;
  ctx.frictionSignals = Object.entries(FRICTION_SIGNALS)
    .filter(([, check]) => check(state))
    .map(([name]) => name);

  // Recent emotional observations (last 5)
  const emotions = state.userObservations?.emotionalState ?? [];
  ctx.recentEmotionalState = emotions.slice(-5);

  // Work style patterns
  ctx.workStyle = state.userObservations?.workStyle ?? [];

  // Task completion patterns — where the user tends to struggle or excel
  ctx.taskCompletionPatterns = state.userObservations?.taskCompletionPatterns ?? [];

  // Goals context — what's driving the user
  ctx.goalsContext = state.userObservations?.goalsContext ?? {};

  // Use hotContext.today as the authoritative date (user timezone, set by summarizer)
  const today = getUserToday(state);
  const cutoff = dateOffset(today, -7);

  // Recent wins — completed tasks from the last 7 days
  ctx.recentWins = state.tasks.tasks
    .filter((t) => t.status === "done" && t.completedAt && t.completedAt.slice(0, 10) >= cutoff)
    .map((t) => t.title)
    .slice(-5);

  // Overdue items — what's weighing on the user
  ctx.overdueItems = state.tasks.tasks
    .filter((t) => t.status !== "done" && t.status !== "deferred" && t.status !== "parked" && t.due && t.due.slice(0, 10) < today)
    .map((t) => ({ title: t.title, due: t.due, priority: t.priority }))
    .slice(0, 5);

  // Communication style — how to talk to this user
  ctx.communicationStyle = state.userObservations?.communicationStyle ?? [];

  // Previous companion brief (if any) — for continuity
  if (state.focusBrief?.companion) {
    ctx.previousCompanion = {
      energyRead: state.focusBrief.companion.energyRead,
      mood: state.focusBrief.companion.mood,
      focusMantra: state.focusBrief.companion.focusMantra,
    };
  }

  return ctx;
}

// buildSupportNote removed — the LLM now handles all support messaging.
// TypeScript detects signals, LLM decides what to say and when.

function estimateEnergy(emotions: string[]): "low" | "medium" | "high" {
  if (
    emotions.some((e) => ["low_energy", "stressed", "anxious"].includes(e))
  )
    return "low";
  if (emotions.includes("positive")) return "high";
  return "medium";
}
