/**
 * FEAT064 — Build-time skill bundler.
 * FEAT067 — Now also pre-computes skill `descriptionEmbedding` at bundle
 * time and emits the vectors into the generated bundle, so web/mobile
 * bundles ship real 384-dim vectors instead of relying on a Node-only
 * runtime compute path. The embedding compute is deterministic given
 * model + input text, so build-time is the right cache layer.
 *
 * Walks src/skills/<id>/, validates each folder has the four required files,
 * and emits src/skills/_generated/skillBundle.ts — a static map keyed by
 * skill id with parsed manifest, raw prompt text, module imports for
 * context.ts and handlers.ts, AND a 384-float `descriptionEmbedding` array.
 *
 * Output is deterministic — sorted lexicographically, no timestamps, no
 * absolute paths, embeddings rounded to consistent precision. Running
 * twice on the same source produces byte-equal output.
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const SKILLS_DIR = path.join(ROOT, "src", "skills");
const GENERATED_DIR = path.join(SKILLS_DIR, "_generated");
const OUTPUT_FILE = path.join(GENERATED_DIR, "skillBundle.ts");

const REQUIRED_FILES = ["manifest.json", "prompt.md", "context.ts", "handlers.ts"];

interface SkillFolder {
  id: string;          // folder name
  manifestId: string;  // manifest.json's id field
  manifest: any;
  promptText: string;
  descriptionEmbedding: number[]; // FEAT067: 384 floats
}

function fail(msg: string): never {
  console.error(`[bundle-skills] ${msg}`);
  process.exit(1);
}

function discoverFolders(): string[] {
  if (!fs.existsSync(SKILLS_DIR)) {
    fail(`skills directory not found: ${SKILLS_DIR}`);
  }
  return fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith("_") && !e.name.startsWith("."))
    .map((e) => e.name)
    .sort();
}

function readSkillFolderBase(folderName: string): {
  id: string;
  manifestId: string;
  manifest: any;
  promptText: string;
} {
  const folderPath = path.join(SKILLS_DIR, folderName);
  for (const f of REQUIRED_FILES) {
    const p = path.join(folderPath, f);
    if (!fs.existsSync(p)) {
      fail(`${folderName}: missing required file ${f} (expected at ${p})`);
    }
  }
  let manifest: any;
  try {
    manifest = JSON.parse(fs.readFileSync(path.join(folderPath, "manifest.json"), "utf-8"));
  } catch (err: any) {
    fail(`${folderName}: malformed manifest.json — ${err?.message ?? err}`);
  }
  if (!manifest || typeof manifest.id !== "string" || manifest.id.length === 0) {
    fail(`${folderName}: manifest.id missing or not a string`);
  }
  if (typeof manifest.description !== "string" || manifest.description.length === 0) {
    fail(`${folderName}: manifest.description missing or not a string`);
  }
  const promptText = fs.readFileSync(path.join(folderPath, "prompt.md"), "utf-8");
  return { id: folderName, manifestId: manifest.id, manifest, promptText };
}

function escapeForRawTemplate(s: string): string {
  // String.raw template literals interpret backticks as terminators and
  // ${...} as interpolation. Escape both so the prompt survives verbatim.
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function camelize(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function emit(folders: SkillFolder[]): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/bundle-skills.ts — do not edit");
  lines.push("// Regenerate via: npm run bundle:skills");
  lines.push("");
  lines.push('import type { SkillManifest, ContextRequirements, ToolHandler } from "../../types/skills";');
  lines.push("");

  // Imports — alphabetical
  for (const f of folders) {
    const cm = camelize(f.id);
    lines.push(`import * as ${cm}Context from "../${f.id}/context";`);
    lines.push(`import * as ${cm}Handlers from "../${f.id}/handlers";`);
    lines.push(`import ${cm}Manifest from "../${f.id}/manifest.json";`);
  }
  lines.push("");

  // Prompt constants
  for (const f of folders) {
    const cm = camelize(f.id);
    const constName = `${f.id.toUpperCase()}_PROMPT`;
    const escaped = escapeForRawTemplate(f.promptText);
    lines.push(`const ${constName} = \`${escaped}\`;`);
    lines.push(`void ${cm}Manifest;`);
  }
  lines.push("");

  // FEAT067 — Skill description embeddings (pre-computed, deterministic)
  for (const f of folders) {
    const constName = `${f.id.toUpperCase()}_EMBEDDING`;
    // Format embedding as a single-line array literal. Each float written
    // via toString() — V8 emits the shortest round-trip representation,
    // which is stable across runs given the same input bytes.
    const formatted = f.descriptionEmbedding.map((v) => v.toString()).join(",");
    lines.push(`const ${constName}: ReadonlyArray<number> = [${formatted}];`);
  }
  lines.push("");

  // Bundle interface
  lines.push("export interface BundledSkill {");
  lines.push("  manifest: SkillManifest;");
  lines.push("  prompt: string;");
  lines.push("  context: { contextRequirements?: ContextRequirements; default?: ContextRequirements } & Record<string, unknown>;");
  lines.push("  handlers: Record<string, ToolHandler>;");
  lines.push("  /** FEAT067 — 384-dim description embedding pre-computed at bundle time. */");
  lines.push("  descriptionEmbedding: ReadonlyArray<number>;");
  lines.push("}");
  lines.push("");

  // Bundle map
  lines.push("export const SKILL_BUNDLE: Record<string, BundledSkill> = {");
  for (const f of folders) {
    const cm = camelize(f.id);
    const constName = `${f.id.toUpperCase()}_PROMPT`;
    const embConstName = `${f.id.toUpperCase()}_EMBEDDING`;
    lines.push(`  ${f.id}: {`);
    lines.push(`    manifest: ${cm}Manifest as unknown as SkillManifest,`);
    lines.push(`    prompt: ${constName},`);
    lines.push(`    context: ${cm}Context as any,`);
    lines.push(`    handlers: ${cm}Handlers as unknown as Record<string, ToolHandler>,`);
    lines.push(`    descriptionEmbedding: ${embConstName},`);
    lines.push(`  },`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const names = discoverFolders();
  const bases = names.map(readSkillFolderBase);

  // Pre-check duplicate manifest ids
  const seen = new Map<string, string>();
  for (const f of bases) {
    if (seen.has(f.manifestId)) {
      fail(`duplicate manifest.id "${f.manifestId}" — folders "${seen.get(f.manifestId)}" and "${f.id}"`);
    }
    seen.set(f.manifestId, f.id);
  }

  // FEAT067 — Compute description embeddings via the provider. The provider
  // is the same one shipped to web; running it on Node here produces the
  // exact vectors the web bundle will compare against query embeddings,
  // ensuring dimension + value parity between index time and query time.
  const { embed } = await import("../src/modules/embeddings/provider");
  const folders: SkillFolder[] = [];
  for (const b of bases) {
    const vec = await embed(b.manifest.description);
    if (!vec || vec.length !== 384) {
      fail(`${b.id}: embedder returned ${vec ? `length ${vec.length}` : "null"} (expected Float32Array(384))`);
    }
    folders.push({
      ...b,
      descriptionEmbedding: Array.from(vec),
    });
    console.log(`[bundle-skills] embedded ${b.id} (${vec.length} dims)`);
  }

  if (!fs.existsSync(GENERATED_DIR)) {
    fs.mkdirSync(GENERATED_DIR, { recursive: true });
  }

  const out = emit(folders);
  // Use LF line endings explicitly for cross-platform determinism.
  const normalized = out.replace(/\r\n/g, "\n");
  fs.writeFileSync(OUTPUT_FILE, normalized, "utf-8");
  console.log(`[bundle-skills] wrote ${folders.length} skills to ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main().catch((err) => {
  console.error("[bundle-skills] failed:", err);
  process.exit(1);
});
