/**
 * FEAT064 — Build-time skill bundler.
 *
 * Walks src/skills/<id>/, validates each folder has the four required files,
 * and emits src/skills/_generated/skillBundle.ts — a static map keyed by
 * skill id with parsed manifest, raw prompt text, and module imports for
 * context.ts and handlers.ts.
 *
 * Web/mobile cannot use fs.readdirSync at runtime, so the registry imports
 * the generated bundle. Node defaults to the bundle too; LIFEOS_SKILL_LIVE_RELOAD=1
 * re-enables the legacy fs walk for skill-author live editing.
 *
 * Output is deterministic — sorted lexicographically, no timestamps, no
 * absolute paths. Running twice on the same source produces byte-equal output.
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const SKILLS_DIR = path.join(ROOT, "src", "skills");
const GENERATED_DIR = path.join(SKILLS_DIR, "_generated");
const OUTPUT_FILE = path.join(GENERATED_DIR, "skillBundle.ts");

const REQUIRED_FILES = ["manifest.json", "prompt.md", "context.ts", "handlers.ts"];

interface SkillFolder {
  id: string;          // folder name
  manifestId: string;  // manifest.json's id field
  manifest: any;
  promptText: string;
}

function fail(msg: string): never {
  console.error(`[bundle-skills] ${msg}`);
  process.exit(1);
}

function discoverFolders(): string[] {
  if (!fs.existsSync(SKILLS_DIR)) {
    fail(`skills directory not found: ${SKILLS_DIR}`);
  }
  return fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith("_") && !e.name.startsWith("."))
    .map((e) => e.name)
    .sort();
}

function readSkillFolder(folderName: string): SkillFolder {
  const folderPath = path.join(SKILLS_DIR, folderName);
  for (const f of REQUIRED_FILES) {
    const p = path.join(folderPath, f);
    if (!fs.existsSync(p)) {
      fail(`${folderName}: missing required file ${f} (expected at ${p})`);
    }
  }
  let manifest: any;
  try {
    manifest = JSON.parse(fs.readFileSync(path.join(folderPath, "manifest.json"), "utf-8"));
  } catch (err: any) {
    fail(`${folderName}: malformed manifest.json — ${err?.message ?? err}`);
  }
  if (!manifest || typeof manifest.id !== "string" || manifest.id.length === 0) {
    fail(`${folderName}: manifest.id missing or not a string`);
  }
  const promptText = fs.readFileSync(path.join(folderPath, "prompt.md"), "utf-8");
  return { id: folderName, manifestId: manifest.id, manifest, promptText };
}

function escapeForRawTemplate(s: string): string {
  // String.raw template literals interpret backticks as terminators and
  // ${...} as interpolation. Escape both so the prompt survives verbatim.
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function camelize(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function emit(folders: SkillFolder[]): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/bundle-skills.ts — do not edit");
  lines.push("// Regenerate via: npm run bundle:skills");
  lines.push("");
  lines.push('import type { SkillManifest, ContextRequirements, ToolHandler } from "../../types/skills";');
  lines.push("");

  // Imports — alphabetical
  for (const f of folders) {
    const cm = camelize(f.id);
    lines.push(`import * as ${cm}Context from "../${f.id}/context";`);
    lines.push(`import * as ${cm}Handlers from "../${f.id}/handlers";`);
    lines.push(`import ${cm}Manifest from "../${f.id}/manifest.json";`);
  }
  lines.push("");

  // Prompt constants
  for (const f of folders) {
    const cm = camelize(f.id);
    const constName = `${f.id.toUpperCase()}_PROMPT`;
    const escaped = escapeForRawTemplate(f.promptText);
    lines.push(`const ${constName} = \`${escaped}\`;`);
    lines.push(`void ${cm}Manifest;`);
  }
  lines.push("");

  // Bundle interface
  lines.push("export interface BundledSkill {");
  lines.push("  manifest: SkillManifest;");
  lines.push("  prompt: string;");
  lines.push("  context: { contextRequirements?: ContextRequirements; default?: ContextRequirements } & Record<string, unknown>;");
  lines.push("  handlers: Record<string, ToolHandler>;");
  lines.push("}");
  lines.push("");

  // Bundle map
  lines.push("export const SKILL_BUNDLE: Record<string, BundledSkill> = {");
  for (const f of folders) {
    const cm = camelize(f.id);
    const constName = `${f.id.toUpperCase()}_PROMPT`;
    lines.push(`  ${f.id}: {`);
    lines.push(`    manifest: ${cm}Manifest as unknown as SkillManifest,`);
    lines.push(`    prompt: ${constName},`);
    lines.push(`    context: ${cm}Context as any,`);
    lines.push(`    handlers: ${cm}Handlers as unknown as Record<string, ToolHandler>,`);
    lines.push(`  },`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const names = discoverFolders();
  const folders = names.map(readSkillFolder);

  // Pre-check duplicate manifest ids
  const seen = new Map<string, string>();
  for (const f of folders) {
    if (seen.has(f.manifestId)) {
      fail(`duplicate manifest.id "${f.manifestId}" — folders "${seen.get(f.manifestId)}" and "${f.id}"`);
    }
    seen.set(f.manifestId, f.id);
  }

  if (!fs.existsSync(GENERATED_DIR)) {
    fs.mkdirSync(GENERATED_DIR, { recursive: true });
  }

  const out = emit(folders);
  // Use LF line endings explicitly for cross-platform determinism.
  const normalized = out.replace(/\r\n/g, "\n");
  fs.writeFileSync(OUTPUT_FILE, normalized, "utf-8");
  console.log(`[bundle-skills] wrote ${folders.length} skills to ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main();
